"""empty message

Revision ID: 0da7c8e5d6d3
Revises: 
Create Date: 2024-05-23 19:24:16.248948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da7c8e5d6d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('createdOn', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', name='roles'), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('panNumber', sa.String(length=50), nullable=False),
    sa.Column('managerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['managerId'], ['employees.employeeId'], ),
    sa.PrimaryKeyConstraint('employeeId'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
